import {EXTRA_COUNTRIES,EXTRA_CASES} from './country-cases.js?v=20261007-5';
// Practical combinations for ordinary public-road GeoGuessr coverage.
// Plate observations concern several ordinary passenger cars, not a lone visitor.
// These are editorial decision rules, not measured probabilities or universal proofs.
export const COUNTRIES={
  ...EXTRA_COUNTRIES,
  nl:{name:'オランダ',native:'Netherlands'},lu:{name:'ルクセンブルク',native:'Luxembourg'},
  be:{name:'ベルギー',native:'Belgium'},it:{name:'イタリア',native:'Italy'},pt:{name:'ポルトガル',native:'Portugal'},
  gb:{name:'イギリス',native:'United Kingdom'},ie:{name:'アイルランド',native:'Ireland'},cy:{name:'キプロス',native:'Cyprus'},
  al:{name:'アルバニア',native:'Albania'},mt:{name:'マルタ',native:'Malta'},fr:{name:'フランス',native:'France'},
  ch:{name:'スイス',native:'Switzerland'},tr:{name:'トルコ',native:'Türkiye'},my:{name:'マレーシア',native:'Malaysia'},
  jp:{name:'日本',native:'Japan'},lk:{name:'スリランカ',native:'Sri Lanka'},
  es:{name:'スペイン',native:'Spain'},de:{name:'ドイツ',native:'Germany'},at:{name:'オーストリア',native:'Austria'},
  li:{name:'リヒテンシュタイン',native:'Liechtenstein'},gr:{name:'ギリシャ',native:'Greece'},
  id:{name:'インドネシア',native:'Indonesia'},th:{name:'タイ',native:'Thailand'},tw:{name:'台湾',native:'Taiwan'},
  in:{name:'インド',native:'India'},sg:{name:'シンガポール',native:'Singapore'},hk:{name:'香港',native:'Hong Kong'},ro:{name:'ルーマニア',native:'Romania'}
};
const plate=(options={})=>({background:'white',letters:'black',left:'none',right:'none',size:'long',...options});
const plates=(front,rear)=>({kind:'plates',label:'一般車のナンバー',front:plate(front),rear:plate(rear)});
const drive=side=>({kind:'drive',side,label:'通行方向'});
const text=(label,value,detail='')=>({kind:'text',label,value,detail});
const sign=(value,shape='octagon')=>({kind:'sign',label:'停止標識',value,shape});
const source=(slug,title)=>({title:title||'Plonk It',url:`https://www.plonkit.net/${slug}`});

export const BASE_COUNTRY_QUESTIONS=[
  {id:'country-001',country:'nl',title:'黄色い前後＋straat',scope:'ヨーロッパ',distractors:['lu','be','gb'],
    clues:[plates({background:'yellow',left:'blue'},{background:'yellow',left:'blue'}),drive('right'),text('街路名','…straat','オランダ語の道路表示')],
    rule:['前後とも黄色','道路名がオランダ語'],
    explanation:'黄色い欧州型ナンバーを見たら、まずオランダを候補に。現地の街路名が -straat などのオランダ語なら、ルクセンブルクとの区別がつきます。',
    compare:[['lu','前後黄色は共通。仏語の案内や枠付きの黄色い方向標識で分ける。'],['be','オランダ語は共通。一般車は白地に赤文字。']],
    note:'黄色いナンバーだけでの出題にはしません。商用車・タクシーは色が異なることがあります。',sources:[source('netherlands'),source('luxembourg'),source('belgium')]},
  {id:'country-002',country:'lu',title:'前後黄色＋仏語の道路案内',scope:'ヨーロッパ',distractors:['nl','be','fr'],
    clues:[plates({background:'yellow',left:'blue'},{background:'yellow',left:'blue'}),text('道路案内','Rue …','フランス語'),text('方向標識','黄地＋黒枠','矢印形・外側を金属枠で囲む')],
    rule:['前後とも黄色','仏語の道路案内','枠付きの黄色い標識'],
    explanation:'オランダと同じ黄色い前後ナンバーでも、公的な案内は主にフランス語。黄地の矢印形標識を囲む枠が、もう一つの決め手です。',
    compare:[['nl','街路名はオランダ語。黄色ナンバーだけでは両国が残る。'],['fr','旧式の後ろ黄色はあるが、前は白。']],
    note:'出題頻度はマップによって変わります。少ない出題でも、この組み合わせを見たときに切り替えます。',sources:[source('luxembourg'),source('netherlands'),source('france')]},
  {id:'country-003',country:'be',title:'白地に赤文字',scope:'ヨーロッパ',distractors:['nl','fr','de'],
    clues:[plates({letters:'red',left:'blue'},{letters:'red',left:'blue'}),drive('right')],
    rule:['白いプレート','文字が赤色'],
    explanation:'注目するのは背景の白より文字の赤。ベルギーの通常ナンバーの強い目印で、ぼかし越しでも赤みが残ることがあります。',
    compare:[['fr','通常は白地に黒文字。右端にも青い帯がある。'],['nl','一般車は前後とも黄色。']],
    note:'赤い背景や、白地に赤い縁取りとは別。登録国の手がかりなので、複数台と現地の道路情報を合わせます。',sources:[source('belgium'),source('france'),source('netherlands')]},
  {id:'country-004',country:'it',title:'前だけ短い＋両端青',scope:'ヨーロッパ',distractors:['fr','al','ch'],
    clues:[plates({left:'blue',right:'blue',size:'short'},{left:'blue',right:'blue'}),drive('right')],
    rule:['前プレートが短い','青帯が左右両端'],
    explanation:'「両端青」だけでなく、前プレートの短さまでセットで見るのが決め手。前と後ろのサイズ差を覚えます。',
    compare:[['fr','両端青でも前は通常の横長。右帯は左帯より細い。'],['al','両端青でも前は通常の横長。'],['ch','前は短いが、青帯がない。']],
    note:'旧式や異なる形のプレートもあります。この形を見つけたときの判定ルールです。',sources:[source('italy'),source('france'),source('albania'),source('switzerland')]},
  {id:'country-005',country:'pt',title:'左青＋右黄の細い帯',scope:'ヨーロッパ',distractors:['es','it','fr'],
    clues:[plates({left:'blue',right:'yellow'},{left:'blue',right:'yellow'}),drive('right')],
    rule:['白いプレート','右端だけ黄色い帯'],
    explanation:'ポルトガルの旧式プレートの目印。左右の帯が青・黄になり、プレート全体が黄色いオランダとは区別できます。',
    compare:[['es','通常は左青・白地で、右の黄色い帯がない。'],['it','両端の帯は青。前は短い。']],
    note:'黄色い帯は2020年に廃止されたため、新しい車にはありません。「見えたら使える」で覚えます。',sources:[source('portugal'),source('spain'),source('italy')]},
  {id:'country-006',country:'gb',title:'前白・後黄＋左＋mile',scope:'ヨーロッパ',distractors:['ie','cy','mt'],
    clues:[plates({},{background:'yellow'}),drive('left'),text('公道の距離表示','MILE / YARDS','マイル・ヤード')],
    rule:['前白・後ろ黄色','左側通行','距離がマイル'],
    explanation:'前白・後黄と左側通行を見てイギリスに寄せ、マイル・ヤードの道路表示で詰めます。青帯は必須ではありません。',
    compare:[['ie','左側通行でも前後白。'],['cy','古い車は前白・後黄だが、ギリシャ語の案内とキロメートルを使う。']],
    note:'前白・後黄＋左側通行だけを、世界共通の英国確定ルールにはしません。',sources:[source('united-kingdom'),source('cyprus'),{title:'英国政府・ナンバー',url:'https://www.gov.uk/displaying-number-plates/rules-number-plates'},{title:'英国政府・道路標識',url:'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/330323/ltn-1-94_design-directional-signs.pdf'}]},
  {id:'country-007',country:'ie',title:'左＋白い前後＋黄色い警戒標識',scope:'ヨーロッパ',distractors:['gb','mt','cy'],
    clues:[plates({left:'blue'},{left:'blue'}),drive('left'),{kind:'warning',label:'警戒標識',value:'黄色いひし形'},text('道路案内','An Lár / City Centre','英語＋アイルランド語。アイルランド語側が斜体')],
    rule:['左側通行','前後白','黄色いひし形の警戒標識'],
    explanation:'ヨーロッパで黄色いひし形の警戒標識が強い決め手。イギリスと似た景観でも、後ろの白ナンバーと二言語の道路案内で分けられます。',
    compare:[['gb','一般車の後ろは黄色。警戒標識は通常、赤枠の三角形。']],
    note:'オーストラリアなどにも黄色いひし形があります。欧州という範囲を含めて使います。',sources:[source('ireland'),source('united-kingdom')]},
  {id:'country-008',country:'cy',title:'ギリシャ文字＋左側通行',scope:'ヨーロッパ',distractors:['gr','mt','gb'],
    clues:[drive('left'),text('公的な道路案内','ΑΓΡΟΣ / Agros','ギリシャ文字と英語の併記')],
    rule:['ギリシャ文字の道路案内','左側通行'],
    explanation:'ギリシャ文字まで読めたら、左右の通行方向を確認。ギリシャは右、キプロスは左です。',
    compare:[['gr','文字は同じでも右側通行。'],['gb','前白・後黄のナンバーは共通することがあるが、ギリシャ文字の道路案内ではない。']],
    note:'キプロスには白い前後ナンバーと、古い後ろ黄色の車が両方あります。',sources:[source('cyprus'),source('greece')]},
  {id:'country-009',country:'al',title:'両端青・前も長い＋Rruga',scope:'ヨーロッパ',distractors:['it','fr','gr'],
    clues:[plates({left:'blue',right:'blue'},{left:'blue',right:'blue'}),text('街路名','Rruga …','rr・ë を含む道路案内')],
    rule:['両端青・前も横長','道路名が Rruga'],
    explanation:'イタリア風の青い両端でも、前が短くない。Rruga という街路名を合わせるとアルバニアを選べます。',
    compare:[['it','前のプレートが短く、街路名は Via が定番。'],['fr','通常の前は横長でも、街路名は Rue。']],
    note:'アルバニアの旧式プレートは左端が赤色のこともあります。青帯がないだけでは除外しません。',sources:[source('albania'),source('italy'),source('france')]},
  {id:'country-010',country:'mt',title:'左側通行＋Triq',scope:'ヨーロッパ',distractors:['gb','ie','cy'],
    clues:[drive('left'),text('街路名','Triq …','マルタ語の「通り」'),text('文字の目印','Ħ・Ċ・Ġ','ラテン文字に横棒・点')],
    rule:['左側通行','道路名の Triq'],
    explanation:'左側通行のヨーロッパで、道路名が Triq。英語の看板が多くても、この街路語を見つければマルタを絞れます。',
    compare:[['cy','左側通行だが、公的な案内にギリシャ文字が現れる。'],['gb','英語は共通するが、街路名の Triq はマルタ語。']],
    note:'石造りの景観だけでなく、現地の街路名を組み合わせます。',sources:[source('malta'),source('cyprus')]},
  {id:'country-011',country:'fr',title:'前も長い・右の青帯が細い＋Rue',scope:'ヨーロッパ',distractors:['it','al','be'],
    clues:[plates({left:'blue',right:'blue-thin'},{left:'blue',right:'blue-thin'}),text('街路名','Rue …','フランス語の道路案内')],
    rule:['前も横長','白地・黒文字・両端青','道路名の Rue'],
    explanation:'長い前プレートとフランス語の街路名を合わせます。右の青帯は左より細く見えるのが現行フランス型の特徴です。',
    compare:[['it','前のプレートが短い。'],['al','前は横長でも、街路名は Rruga。'],['be','仏語を使う地域はあるが、通常ナンバーは赤文字。']],
    note:'古いフランス車には後ろが黄色いものもあります。新旧を混ぜて否定条件にしません。',sources:[source('france'),source('italy'),source('albania'),source('belgium')]},
  {id:'country-012',country:'ch',title:'前が短い・青帯なし＋黄色い横断歩道',scope:'ヨーロッパ',distractors:['it','li','at'],
    clues:[plates({size:'short'},{emblem:true}),{kind:'crosswalk',label:'横断歩道',value:'黄色いしま模様'},drive('right')],
    rule:['前が短い白ナンバー','青帯なし','黄色い横断歩道'],
    explanation:'黄色い横断歩道に、青帯のない短い白い前プレートを合わせます。後ろの白プレートに赤い国章も見えればスイス型を確認できます。',
    compare:[['li','横断歩道は似るが、通常ナンバーは黒地に白文字。'],['it','短い前でも左右の青帯がある。']],
    note:'国境付近ではスイス車が隣国にも来ます。白プレート一台だけを撮影国の保証にはしません。',sources:[source('switzerland'),source('liechtenstein'),source('italy')]},
  {id:'country-013',country:'tr',title:'停止標識の DUR',scope:'通常の道路カバレッジ',distractors:['ro','gr','al'],
    clues:[sign('DUR'),drive('right')],rule:['赤い八角形','DUR'],
    explanation:'普通の文章の dur ではなく、停止標識の DUR。トルコを選ぶ強い決め手として、標識の形と文字を一緒に覚えます。',
    compare:[['fr','dur という単語はあるが、通常の停止標識は STOP。']],
    note:'外国語の看板の一語として出た場合には、この標識ルールを当てはめません。',sources:[source('turkey'),source('france')]},
  {id:'country-014',country:'my',title:'停止標識の BERHENTI',scope:'通常の道路カバレッジ',distractors:['id','sg','th'],
    clues:[sign('BERHENTI'),drive('left')],rule:['赤い八角形','BERHENTI'],
    explanation:'jalan ではマレー語とインドネシア語が残りますが、停止標識の BERHENTI ならマレーシアの強い決め手になります。',
    compare:[['id','berhenti という単語自体はある。普通の文章と停止標識を区別する。']],
    note:'このルールの対象は通常のジオゲの道路カバレッジです。',sources:[source('malaysia')]},
  {id:'country-015',country:'jp',title:'赤い逆三角形＋止まれ',scope:'通常の道路カバレッジ',distractors:['tw','th','hk'],
    clues:[sign('止まれ','triangle-down'),drive('left')],rule:['赤い逆三角形','止まれ','左側通行'],
    explanation:'漢字一字ではなく、「止まれ」のひらがなと逆三角形をセットで見ると日本の停止標識を見分けられます。',
    compare:[['tw','漢字はあるが右側通行。'],['hk','左側通行でも、公的な停止標識の日本語「止まれ」ではない。']],
    note:'新しい標識には STOP が併記されるものもあります。',sources:[source('japan'),{title:'JAF・交通標識',url:'https://english.jaf.or.jp/safe-driving/quiz/motorvehicles'}]},
  {id:'country-016',country:'lk',title:'前白・後黄＋シンハラ文字',scope:'南アジア',distractors:['in','th','my'],
    clues:[plates({},{background:'yellow',size:'short'}),drive('left'),text('公的な看板','සිංහල','シンハラ文字')],
    rule:['左側通行','前白・後黄','シンハラ文字'],
    explanation:'前白・後黄はイギリス専用ではありません。丸いシンハラ文字の現地看板まで合わせると、スリランカを選べます。',
    compare:[['in','タミル文字はインドにもあるが、シンハラ文字と混同しない。'],['gb','前後の色と左側通行は似るが、公的な看板の文字が異なる。']],
    note:'タミル文字だけではスリランカとインドを分けられません。',sources:[source('sri-lanka')]}
];

export const COUNTRY_QUESTIONS=[...BASE_COUNTRY_QUESTIONS,...EXTRA_CASES.filter(c=>c.quiz).map(c=>({
  id:c.id,country:c.country,title:c.title,scope:c.area,distractors:c.distractors,
  clues:[...c.observations.map((value,i)=>({kind:'observation',label:`観察 ${i+1}`,value})),
    ...(c.photos.length?[{kind:'photo',label:'参考写真',photos:c.photos}]:[])],
  rule:c.observations,explanation:c.summary,compare:c.compare,note:c.note,sources:c.sources,next:c.next,
  steps:c.steps
}))];
