// Photo provenance and published, pre-mosaicked assets.
export const PHOTOS = {
  "nl": {
    "title": "File:Netherlands licenseplate present.JPG",
    "src": "assets/photos/nl-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Netherlands_licenseplate_present.JPG",
    "width": 2171,
    "height": 724,
    "author": "Dickelbers",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "lu": {
    "title": "File:Luxembourg license plate CK 1953.jpg",
    "src": "assets/photos/lu-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Luxembourg_license_plate_CK_1953.jpg",
    "width": 2171,
    "height": 724,
    "author": "2538O",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "kind": "photo",
    "label": "ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "be": {
    "title": "File:Belgium license plate 2-FRE-656.jpg",
    "src": "assets/photos/be-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Belgium_license_plate_2-FRE-656.jpg",
    "width": 2171,
    "height": 724,
    "author": "2538O",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "kind": "photo",
    "label": "ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "al": {
    "title": "File:License plate Albania New.jpg",
    "src": "assets/photos/al-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:License_plate_Albania_New.jpg",
    "width": 2170,
    "height": 725,
    "author": "Albinfo",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "kind": "photo",
    "label": "ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "pt": {
    "title": "File:License plate of Portugal.JPG",
    "src": "assets/photos/pt-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:License_plate_of_Portugal.JPG",
    "width": 2171,
    "height": 724,
    "author": "Dickelbers",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "旧型ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "fr": {
    "title": "File:French License Plate 21052009.JPG",
    "src": "assets/photos/fr-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:French_License_Plate_21052009.JPG",
    "width": 2169,
    "height": 725,
    "author": "Svbzc",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "ie": {
    "title": "File:2020 Irish license plate.jpg",
    "src": "assets/photos/ie-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:2020_Irish_license_plate.jpg",
    "width": 2171,
    "height": 724,
    "author": "Walser123",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "ua": {
    "title": "File:Ukraine license plate AT7548CT.jpg",
    "src": "assets/photos/ua-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Ukraine_license_plate_AT7548CT.jpg",
    "width": 1536,
    "height": 1024,
    "author": "Matej Grochal",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "左端の青と黄",
    "plate": true,
    "mosaic": true
  },
  "co": {
    "title": "File:License plate of Popayán.jpg",
    "src": "assets/photos/co-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:License_plate_of_Popay%C3%A1n.jpg",
    "width": 1536,
    "height": 1024,
    "author": "Bernard Gagnon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "黄色いナンバー",
    "plate": true,
    "mosaic": true
  },
  "it-front": {
    "title": "File:Targa automobilistica Italia 1999 format HB•778SG Torino (anteriore).jpg",
    "src": "assets/photos/it-front-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Targa_automobilistica_Italia_1999_format_HB%E2%80%A2778SG_Torino_(anteriore).jpg",
    "width": 2170,
    "height": 725,
    "author": "Edera1970",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "kind": "photo",
    "label": "前",
    "plate": true,
    "mosaic": true
  },
  "it-rear": {
    "title": "File:Targa automobilistica Italia 1999 format HB•778SG Torino (posteriore).jpg",
    "src": "assets/photos/it-rear-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Targa_automobilistica_Italia_1999_format_HB%E2%80%A2778SG_Torino_(posteriore).jpg",
    "width": 2171,
    "height": 724,
    "author": "Edera1970",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "kind": "photo",
    "label": "後",
    "plate": true,
    "mosaic": true
  },
  "gb-front": {
    "title": "File:1992 Lancia Y10 LX Selectronic (14983161489).jpg",
    "src": "assets/photos/gb-front-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:1992_Lancia_Y10_LX_Selectronic_(14983161489).jpg",
    "width": 1536,
    "height": 1024,
    "author": "Charlie from United Kingdom",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "kind": "photo",
    "label": "前",
    "plate": true,
    "mosaic": true
  },
  "gb-rear": {
    "title": "File:1992 Lancia Y10 LX Selectronic (15170029385).jpg",
    "src": "assets/photos/gb-rear-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:1992_Lancia_Y10_LX_Selectronic_(15170029385).jpg",
    "width": 1536,
    "height": 1024,
    "author": "Charlie from United Kingdom",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "kind": "photo",
    "label": "後",
    "plate": true,
    "mosaic": true
  },
  "ch-pair": {
    "title": "File:Switzerland Zürich front and rear license plate.jpg",
    "src": "assets/photos/ch-pair-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Switzerland_Z%C3%BCrich_front_and_rear_license_plate.jpg",
    "width": 1717,
    "height": 916,
    "author": "Dickelbers",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "上：前 ／ 下：後（別縮尺）",
    "plate": true,
    "mosaic": true
  },
  "lk-front": {
    "title": "File:Front Side of A Vehicle Number Plate.jpg",
    "src": "assets/photos/lk-front-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Front_Side_of_A_Vehicle_Number_Plate.jpg",
    "width": 2169,
    "height": 725,
    "author": "Knadeeshana",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "白い前ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "lk-rear": {
    "title": "File:Rear Side of a Vehicle Number Plate.jpg",
    "src": "assets/photos/lk-rear-mosaic.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Rear_Side_of_a_Vehicle_Number_Plate.jpg",
    "width": 1651,
    "height": 953,
    "author": "Knadeeshana",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "黄色い後ナンバー例",
    "plate": true,
    "mosaic": true
  },
  "dur": {
    "title": "File:Stop sign, Beyoğlu 7May23.jpg",
    "src": "assets/photos/dur.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Stop_sign,_Beyo%C4%9Flu_7May23.jpg",
    "width": 1200,
    "height": 1600,
    "author": "Mariam elr",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "DUR",
    "plate": false
  },
  "berhenti": {
    "title": "File:Malaysia Traffic-signs Regulatory-sign-02.jpg",
    "src": "assets/photos/berhenti.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Malaysia_Traffic-signs_Regulatory-sign-02.jpg",
    "width": 1200,
    "height": 1200,
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "BERHENTI",
    "plate": false
  },
  "japan-stop": {
    "title": "File:Stop Sign in Japan with English 2019.jpg",
    "src": "assets/photos/japan-stop.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Stop_Sign_in_Japan_with_English_2019.jpg",
    "width": 1200,
    "height": 2133,
    "author": "秋霖驟雨",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "止まれ",
    "plate": false
  },
  "pare": {
    "title": "File:StopSignSãoPaulo.jpg",
    "src": "assets/photos/pare.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:StopSignS%C3%A3oPaulo.jpg",
    "width": 1200,
    "height": 1200,
    "author": "OperaJoeGreen at English Wikipedia",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "kind": "photo",
    "label": "PARE",
    "plate": false
  },
  "nz-shield": {
    "title": "File:State Highway 6 Sign.jpg",
    "src": "assets/photos/nz-shield.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:State_Highway_6_Sign.jpg",
    "width": 1200,
    "height": 1600,
    "author": "Ulrich Lange, Dunedin, New Zealand",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "kind": "photo",
    "label": "赤い路線番号の盾",
    "plate": false
  },
  "nz-giveway": {
    "title": "File:2011vmv Giveway2.jpg",
    "src": "assets/photos/nz-giveway.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:2011vmv_Giveway2.jpg",
    "width": 1200,
    "height": 1607,
    "author": "Virtualmv",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "赤文字の GIVE WAY",
    "plate": false
  },
  "speed-us": {
    "title": "File:10 US Highway speed limit sign 55 MPH - Garfield County, Colorado.jpg",
    "src": "assets/photos/speed-us.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:10_US_Highway_speed_limit_sign_55_MPH_-_Garfield_County,_Colorado.jpg",
    "width": 1200,
    "height": 800,
    "author": "Marek Ślusarczyk (Tupungato) Photo portfolio",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "kind": "photo",
    "label": "SPEED LIMIT",
    "plate": false
  },
  "speed-ca": {
    "title": "File:Maximum 120 sign in BC.JPG",
    "src": "assets/photos/speed-ca.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Maximum_120_sign_in_BC.JPG",
    "width": 1200,
    "height": 796,
    "author": "Amateria1121",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "MAXIMUM",
    "plate": false
  },
  "thai-stop": {
    "title": "File:Thailand Traffic-signs Regulatory-sign-01a.jpg",
    "src": "assets/photos/thai-stop.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Thailand_Traffic-signs_Regulatory-sign-01a.jpg",
    "width": 1200,
    "height": 1200,
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "หยุด",
    "plate": false
  },
  "lao-stop": {
    "title": "File:Luang-Prabang Laos Stop-Sign-01.jpg",
    "src": "assets/photos/lao-stop.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Luang-Prabang_Laos_Stop-Sign-01.jpg",
    "width": 1200,
    "height": 1200,
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "ຢຸດ",
    "plate": false
  },
  "korean-sign": {
    "title": "File:Korean Road Name Sign - Gangbyeonbukro.jpg",
    "src": "assets/photos/korean-sign.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Korean_Road_Name_Sign_-_Gangbyeonbukro.jpg",
    "width": 1200,
    "height": 900,
    "author": "P.Cps1120a",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "ハングルの街路名",
    "plate": false
  },
  "khmer-sign": {
    "title": "File:Road signs in Cambodia. Electricity Factory 5 km.jpg",
    "src": "assets/photos/khmer-sign.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Road_signs_in_Cambodia._Electricity_Factory_5_km.jpg",
    "width": 1200,
    "height": 800,
    "author": "Dmitry Makeev",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "クメール文字の案内",
    "plate": false
  },
  "greek-sign": {
    "title": "File:Directional road signs in Greece.jpg",
    "src": "assets/photos/greek-sign.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Directional_road_signs_in_Greece.jpg",
    "width": 1200,
    "height": 3333,
    "author": "International Driving Authority",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "ギリシャ文字の道路案内",
    "plate": false
  },
  "cy-sign": {
    "title": "File:Agros, Cyprus Road Sign.jpg",
    "src": "assets/photos/cy-sign.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Agros,_Cyprus_Road_Sign.jpg",
    "width": 1200,
    "height": 1600,
    "author": "Xaris333",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "ギリシャ文字＋英語",
    "plate": false
  },
  "volcano": {
    "title": "File:View of Ögmundarhraun lava field in Iceland from Road 427.jpg",
    "src": "assets/photos/volcano.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:View_of_%C3%96gmundarhraun_lava_field_in_Iceland_from_Road_427.jpg",
    "width": 1200,
    "height": 796,
    "author": "Alexander Grebenkov",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "kind": "photo",
    "label": "溶岩原と道路",
    "plate": false
  },
  "lesotho": {
    "title": "File:Maloti Mountains Village.jpg",
    "src": "assets/photos/lesotho.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Maloti_Mountains_Village.jpg",
    "width": 1200,
    "height": 523,
    "author": "SkyPixels",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "高地・集落",
    "plate": false
  },
  "drive-left": {
    "title": "File:Drive-on-the-left-kent-1b.jpg",
    "src": "assets/photos/drive-left.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Drive-on-the-left-kent-1b.jpg",
    "width": 1200,
    "height": 855,
    "author": "w:User:NFH, w:User:John",
    "license": "Public domain",
    "licenseUrl": "",
    "kind": "photo",
    "label": "左側通行の案内",
    "plate": false
  },
  "id-address": {
    "title": "File:Gerbang Selamat Datang di Kabupaten Kapuas.JPG",
    "src": "assets/photos/id-address.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Gerbang_Selamat_Datang_di_Kabupaten_Kapuas.JPG",
    "width": 1200,
    "height": 798,
    "author": "Ezagren (bicara / talk)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "行政区域の入口",
    "plate": false
  },
  "crosswalk": {
    "title": "File:Lowered kerb at pedestrian crossing.jpg",
    "src": "assets/photos/crosswalk.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Lowered_kerb_at_pedestrian_crossing.jpg",
    "width": 1200,
    "height": 800,
    "author": "SelfishSeahorse",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "kind": "photo",
    "label": "黄色い横断歩道",
    "plate": false
  },
  "malta": {
    "title": "File:Mdina street 2024.jpg",
    "src": "assets/photos/malta.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Mdina_street_2024.jpg",
    "width": 1200,
    "height": 1516,
    "author": "Jaakko.kulta",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "kind": "photo",
    "label": "石灰岩の街並み",
    "plate": false
  },
  "netherlands": {
    "title": "File:De ligfiets langs het Rasquerter Maar bij Tinallinge (35660698383).jpg",
    "src": "assets/photos/netherlands.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:De_ligfiets_langs_het_Rasquerter_Maar_bij_Tinallinge_(35660698383).jpg",
    "width": 1200,
    "height": 800,
    "author": "m66roepers from Nederland",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "kind": "photo",
    "label": "平地と水路",
    "plate": false
  },
  "road-centre": {
    "title": "File:Bilvei, Karin Beate Nosterud.jpg",
    "src": "assets/photos/road-centre.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Bilvei,_Karin_Beate_Nosterud.jpg",
    "width": 1200,
    "height": 798,
    "author": "Karin Beate Nøsterud",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "kind": "photo",
    "label": "黄の中央線・白の外側線",
    "plate": false
  },
  "triq": {
    "title": "File:Malta - Qormi - Triq Antonio Muscat Fenech - 1.jpg",
    "src": "assets/photos/triq.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Malta_-_Qormi_-_Triq_Antonio_Muscat_Fenech_-_1.jpg",
    "width": 1200,
    "height": 900,
    "author": "Pygar1954",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "Triq",
    "plate": false
  },
  "rue": {
    "title": "File:Plaque Rue Damesme - Paris XIII (FR75) - 2021-07-21 - 3.jpg",
    "src": "assets/photos/rue.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Plaque_Rue_Damesme_-_Paris_XIII_(FR75)_-_2021-07-21_-_3.jpg",
    "width": 1200,
    "height": 997,
    "author": "Chabe01",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "kind": "photo",
    "label": "Rue",
    "plate": false
  },
  "ireland-warning": {
    "title": "File:A bend in the road, Ray - geograph.org.uk - 2602744.jpg",
    "src": "assets/photos/ireland-warning.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:A_bend_in_the_road,_Ray_-_geograph.org.uk_-_2602744.jpg",
    "width": 1200,
    "height": 900,
    "author": "Kenneth  Allen",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "kind": "photo",
    "label": "黄色いひし形",
    "plate": false
  },
  "dk-sign": {
    "title": "File:Roadsign towards Copenhagen.jpg",
    "src": "assets/photos/dk-sign.jpg",
    "source": "https://commons.wikimedia.org/wiki/File:Roadsign_towards_Copenhagen.jpg",
    "width": 1200,
    "height": 898,
    "author": "Leif Jørgensen",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "kind": "photo",
    "label": "赤白の矢印・パイプ枠",
    "plate": false
  },
  "pole-ro": {
    "src": "assets/photos/pole-ro-generated.jpg",
    "width": 1536,
    "height": 1024,
    "label": "大きい黄色い札",
    "kind": "generated",
    "plate": false,
    "author": "AI生成",
    "license": "Generated reference",
    "source": "./PHOTO_CREDITS.md"
  },
  "pole-tw": {
    "src": "assets/photos/pole-tw-generated.jpg",
    "width": 1536,
    "height": 1024,
    "label": "地面まで続く黄黒の帯",
    "kind": "generated",
    "plate": false,
    "author": "AI生成",
    "license": "Generated reference",
    "source": "./PHOTO_CREDITS.md"
  },
  "pole-lk": {
    "src": "assets/photos/pole-lk-generated.jpg",
    "width": 1536,
    "height": 1024,
    "label": "下部の大きな穴",
    "kind": "generated",
    "plate": false,
    "author": "AI生成",
    "license": "Generated reference",
    "source": "./PHOTO_CREDITS.md"
  },
  "sign-cross": {
    "src": "assets/photos/sign-cross-generated.jpg",
    "width": 1536,
    "height": 1024,
    "label": "標識の裏の白い十字",
    "kind": "generated",
    "plate": false,
    "author": "AI生成",
    "license": "Generated reference",
    "source": "./PHOTO_CREDITS.md"
  },
  "sun": {
    "src": "assets/photos/sun-generated.jpg",
    "width": 1536,
    "height": 1024,
    "label": "太陽と影の観察例",
    "kind": "generated",
    "plate": false,
    "author": "AI生成",
    "license": "Generated reference",
    "source": "./PHOTO_CREDITS.md"
  },
  "road-africa": {
    "src": "assets/photos/road-africa-generated.jpg",
    "width": 1536,
    "height": 1024,
    "label": "黄の外側線・白の中央線",
    "kind": "generated",
    "plate": false,
    "author": "AI生成",
    "license": "Generated reference",
    "source": "./PHOTO_CREDITS.md"
  },
  "mx-shield": {
    "src": "assets/photos/mx-shield-generated.jpg",
    "width": 1536,
    "height": 1024,
    "label": "MEXICO の路線番号標識",
    "kind": "generated",
    "plate": false,
    "author": "AI生成",
    "license": "Generated reference",
    "source": "./PHOTO_CREDITS.md"
  }
};

export const PLATE_PHOTOS = {
  nl:[['nl','前後共通の型']],lu:[['lu','前後共通の型']],be:[['be','前後共通の型']],
  it:['it-front','it-rear'],pt:[['pt','前後共通の型（旧型）']],gb:['gb-front','gb-rear'],
  ie:[['ie','前後共通の型']],al:[['al','前後共通の型']],fr:[['fr','前後共通の型']],
  ch:['ch-pair'],lk:['lk-front','lk-rear']
};
export const VISUAL_PHOTOS = {
  'sun-south':['sun'],'sun-north':['sun'],volcano:['volcano'],'table-mountain':['lesotho'],
  'stone-town':['malta'],'flat-land':['netherlands'],'road-africa':['road-africa'],
  'drive-left':['drive-left'],crosswalk:['crosswalk'],'greek-drive':['cy-sign','greek-sign'],
  'road-centre':['road-centre'],'pole-yellow':['pole-ro'],'pole-stripes':['pole-tw'],
  'pole-holes':['pole-lk'],'stop-dur':['dur'],'stop-berhenti':['berhenti'],
  'stop-japan':['japan-stop'],warning:['ireland-warning'],'pipe-sign':['dk-sign'],
  'stop-pare':['pare'],'giveway-red':['nz-giveway','nz-shield'],'sign-cross':['sign-cross'],
  'plate-ukraine':['ua'],'plate-yellow':['co'],'speed-compare':['speed-us','speed-ca'],
  'mexico-shield':['mx-shield'],'thai-lao':['thai-stop','lao-stop'],
  'script-compare':['korean-sign','khmer-sign']
};
export const ROUTE_PHOTOS = {
  greece:['greek-sign'],iceland:['volcano'],romania:['pole-ro'],taiwan:['pole-tw'],
  denmark:['dk-sign'],colombia:['co','sign-cross'],brazil:['pare'],ukraine:['ua'],
  'new-zealand':['nz-giveway','nz-shield'],'southern-africa':['road-africa'],
  'lesotho-region':['lesotho'],'united-states':['speed-us'],canada:['speed-ca'],
  mexico:['mx-shield'],'south-korea':['korean-sign'],cambodia:['khmer-sign'],
  thailand:['thai-stop'],laos:['lao-stop'],indonesia:['id-address']
};
